language: node_js

node_js:
  - "10.16"

before_deploy:
  - ./scripts/get-npm-token-from-env

deploy:
  provider: script
  script: "npm test"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
      - can.maintainer@gmail.com 
    on_success: change
    on_failure: always
