version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.13

jobs:
  test-and-lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-v1-{{ checksum "package.json" }}
            - cache-v1- # fallback match
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: cache-v1-{{ checksum "package.json" }}
      - run: npm run test
      - run: npm run lint         
      - persist_to_workspace:
          root: ~/repo
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build package
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm run publish-to-npmjs

workflows:
  version: 2
  test:
    jobs:
      - test-and-lint
      - build:
         filters:
            branches:
              only: master
         requires:
           - test-and-lint
      - hold:
          type: approval
          requires:
            - build
      - publish:
          requires:
            - hold
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
