version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12.13

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key:
            - {{ .CACHE_VERSION }}-{{ checksum "package.json" }}
            - {{ .CACHE_VERSION }}- # fallback match
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: {{ .CACHE_VERSION }}-{{ checksum "package.json" }}
      - run: npm test

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      # - deploy:
      #     requires:
      #       - test
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
